name: CD

on:
  push:
    branches: [ mshci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    # - name: Build
    #   run: npm run build
    - name: Make dist folder
      run: mkdir dist

    - name: Copy CNAME
      run: cp CNAME dist/

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        cp -r src/* dist
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
